version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=no
      - ZOO_ENABLE_AUTH=yes
      - KAFKA_ZOOKEEPER_PROTOCOL=SAsL
      - ZOO_SERVER_USERS=citisquare
      - ZOO_SERVER_PASSWORDS=citisquare-zookeeper
  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_PROTOCOL:SASL
      - KAFKA_ZOOKEEPER_USER:citisquare
      - KAFKA_ZOOKEEPER_PASSWORD:citisquare-zookeeper
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092    
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      # - KAFKA_CLIENT_USERS=citisquare
      # - KAFKA_CLIENT_PASSWORDS=citisquare-zookeeper
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local